### ISSUE TITLE
npm run build:types fails in v2.2.x

### ISSUE THREAD

**Issue by fculpo** [nodecg/nodecg#750]
On a fresh clone of any NodeCG v2.2.x (tested all 3 releases), npm run build fails when building types. 
This seems ws/socket.io related.

Works fine on v2.1.x version.

```shell
❯ node --version
v18.20.4

❯ npm --version
10.7.0

❯ npm run build:types

> nodecg@2.2.2 build:types
> ts-node scripts/generate-types-package.ts

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported

added 166 packages, and audited 167 packages in 18s

14 packages are looking for funding
  run `npm fund` for details

2 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix --force

Run `npm audit` for details.
node_modules/engine.io-client/build/esm/transports/websocket.node.d.ts:12:108 - error TS7016: Could not find a declaration file for module 'ws'. '/somepath/nodecg/generated-types/node_modules/ws/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/ws` if it exists or add a new declaration (.d.ts) file containing `declare module 'ws';`

12     createSocket(uri: string, protocols: string | string[] | undefined, opts: Record<string, any>): import("ws");
                                                                                                              ~~~~


Found 1 error in node_modules/engine.io-client/build/esm/transports/websocket.node.d.ts:12

Error: Command failed: npx tsc
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at Object.<anonymous> (/somepath/nodecg/scripts/generate-types-package.ts:22:10)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module.m._compile (/somepath/nodecg/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Object.require.extensions.<computed> [as .ts] (/somepath/nodecg/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1019:12) {
  status: 2,
  signal: null,
  output: [ null, null, null ],
  pid: 56875,
  stdout: null,
  stderr: null
}
```
